Repository Azure/CCOInsights, pull requests merged in 2020-06, with the labels that each got.

#95 New Blueprints Images
  docs/assets/2020_Icons/AssignedBlueprints.svg
  docs/assets/2020_Icons/BlueprintAssignedSubscriptionKind.svg
  docs/assets/2020_Icons/BlueprintRoleContributorKind.svg
  docs/assets/2020_Icons/BlueprintTemplateKind.svg
  docs/assets/2020_Icons/Policy.svg
  docs/assets/2020_Icons/PolicyAssignments.svg
  docs/assets/2020_Icons/PolicyDefinitions.svg
Labels: Update

#98 Develop/customconnector gov
  src/CustomConnectors/CcoDashboardAzureConnector/CcoDashboardAzureConnector.mproj
  src/CustomConnectors/CcoDashboardAzureConnector/CcoDashboardAzureConnector.pq
  src/CustomConnectors/CcoDashboardAzureConnector/CcoDashboardAzureConnector.query.pq
  src/CustomConnectors/CcoDashboardAzureConnector/client_id_global
  src/CustomConnectors/CcoDashboardAzureConnector/client_id_govus
Labels: enhancement

#101 Update README.md
  README.md
Labels: Documentation update

#102 Adding 2020 Azure Icons to the library
  docs/assets/2020_Icons/AzureDevOps.svg
  docs/assets/2020_Icons/BCDR.svg
  docs/assets/2020_Icons/Identity.svg
  docs/assets/2020_Icons/Tenant.svg
  docs/assets/2020_Icons/VirtualWANs.svg
Labels: Documentation update
