Repository Azure/CCOInsights, pull requests merged in 2020-01, with the labels that each got.

#56 BUGFIX: Azure Security Center URLs
  README.md
  dashboards/CCODashboard/CCO Power BI Dashboard v6.2.pbit
  dashboards/CCODashboard/Old Versions/CCO Power BI Dashboard v6.1 GitHub Final.pbit
Labels: bug

#58 Security Recommendations file added
  README.md
  dashboards/CCODashboard/CCO Power BI Dashboard v6.1 GitHub Final.pbit
  docs/assets/SecRec.md
Labels: enhancement

#59 CCO Dashboard 6.3 updated
  dashboards/CCODashboard/CCO Power BI Dashboard v6.2.pbit
  dashboards/CCODashboard/Old Versions/CCO Power BI Dashboard v6.2.pbit
  docs/assets/SecRec.md
Labels: bug

#64 MG image
  docs/assets/pictures/037_Management Groups.svg
Labels: Update

#65 MG Image Name Update
  docs/assets/pictures/037_Management_Groups.svg
Labels: Update
